login:
    path: /login
    defaults: { _controller: MyShopAdminBundle:Login:login }

my_shop_admin.index:
    path:     /
    defaults: { _controller: MyShopAdminBundle:Default:index }

my_shop_admin.product_add:
    path:   /product/add
    defaults: { _controller: MyShopAdminBundle:Product:add }

my_shop_admin.product_list:
    path:   /product/list
    defaults: { _controller: MyShopAdminBundle:Product:list }

my_shop.admin.product_delete:
    path:   /product/{id}/delete
    defaults: { _controller: MyShopAdminBundle:Product:delete }
    requirements:
        id: \d+

my_shop_admin.product_edit:
    path:   /product/{id}/edit
    defaults: { _controller: MyShopAdminBundle:Product:edit }
    requirements:
        id: \d+

my_shop_admin.category_add:
    path:   /category/add
    defaults: { _controller: MyShopAdminBundle:Category:add }

my_shop_admin.category_list:
    path:   /category/list
    defaults: { _controller: MyShopAdminBundle:Category:list }

my_shop_admin.product_list_by_category:
    path:   /category/{id_category}/product/list
    defaults: { _controller: MyShopAdminBundle:Product:listByCategory }
    requirements:
        id_category: \d+

my_shop_admin.category_delete:
    path:   /category/{id_category}/delete
    defaults: { _controller: MyShopAdminBundle:Category:delete }
    requirements:
        id_category: \d+

my_shop_admin.category_edit:
    path:   /category/{id_category}/edit
    defaults: { _controller: MyShopAdminBundle:Category:edit }
    requirements:
        id_category: \d+

my_shop.admin.category_icon_delete:
    path:   /category_icon/{id_category}/delete
    defaults: { _controller: MyShopAdminBundle:Category:deleteIcon }
    requirements:
        id_category: \d+        

my_shop_admin.product_photo_add:
    path:   /product/{idProduct}/photo/add
    defaults: { _controller: MyShopAdminBundle:ProductPhoto:add }
    requirements:
        idProduct: \d+

my_shop_admin.product_photo_list:
    path:   /product/{idProduct}/photos
    defaults: { _controller: MyShopAdminBundle:ProductPhoto:list }
    requirements:
        idProduct: \d+

my_shop_admin.product_photo_delete:
    path:   /product/{id}/photo/delete
    defaults: { _controller: MyShopAdminBundle:ProductPhoto:delete }
    requirements:
        id: \d+

my_shop_admin.product_photo_edit:
    path:   /product/{id}/photo/edit
    defaults: { _controller: MyShopAdminBundle:ProductPhoto:edit }
    requirements:
        id: \d+
my_shop_admin.user_add:
    path: /user/add
    defaults: { _controller: MyShopAdminBundle:User:add }

my_shop_admin.load_some_users:
    path: /load/some/users
    defaults: { _controller: MyShopAdminBundle:Default:loadUsers}

my_shop_admin.load_some_users:
    path: /load/some/users
    defaults: { _controller: MyShopAdminBundle:Default:loadUsers}    

my_shop_admin.load_some_products:
    path: /load/some/products
    defaults: { _controller: MyShopAdminBundle:Default:loadProduct}    
