myshop.product_info:
    path:     /{id}
    defaults: { _controller: MyShopDefaultBundle:Default:showProduct }
    methods: [GET]
    requirements:
        id: \d+

myshop.main_page:
    path:    / 
    defaults: { _controller: MyShopDefaultBundle:Default:index }

myshop.product_list:
    path: /product/list
    defaults: { _controller: MyShopDefaultBundle:Default:showProductList }

myshop.product_comments:
    path: /product/comments/{id}
    defaults: { _controller: MyShopDefaultBundle:Default:showComment }
    requirements:
        id: \d+


myshop.category_list:
    path: /category/list
    defaults: { _controller: MyShopDefaultBundle:Default:showCategoryList }
    

