myshop.product_info:
    path:     /{id}
    defaults: { _controller: MyShopDefaultBundle:Default:showProduct }
    methods: [GET]
    requirements:
        id: \d+

myshop.main_page:
    path:    / 
    defaults: { _controller: MyShopDefaultBundle:Default:index }

myshop.product_list:
    path: /product/list
    defaults: { _controller: MyShopDefaultBundle:Default:showProductList }

myshop.product_comments:
    path: /product/comments/{id}
    defaults: { _controller: MyShopDefaultBundle:Default:showComment }
    requirements:
        id: \d+


myshop.category_list:
    path: /category/list
    defaults: { _controller: MyShopDefaultBundle:Default:showCategoryList }

myshop.api_product:
    path: /api/product/{id}
    defaults: { _controller: MyShopDefaultBundle:API/REST/Product:details }
    requirements:
        id: \d+

myshop.api_products:
    path: /api/products
    defaults: { _controller: MyShopDefaultBundle:API/REST/Product:list }
    
myshop.api_photos:
    path: /api/photos/
    defaults: { _controller: MyShopDefaultBundle:API/REST/Product:photo }

myshop.api_photo_details:
    path: /api/photo/{idProduct}
    defaults: { _controller: MyShopDefaultBundle:API/REST/Product:photoDetails }
    requirements:
        idProduct: \d+
